### PR TITLE
acatangiu-2024-H1 evidence for retain rank 2

### PR DESCRIPTION
**Pull request by acatangiu**
Dear Fellows,

I am submitting this evidence covering my recent relevant activity in the Polkadot ecosystem, with the intention of retaining rank 2.

You can see the [rendered version here](https://github.com/acatangiu/Evidences/blob/main/evidence/acatangiu/0001-acatangiu-2024-H1-evidence.md).

Blake2-256 hash of the file: `71e08b12e9d8ad8cbab2a09a95349b7894bcdfe3b45e723f30e990739f46efc2`

### CODE REVIEW

**Comment by acatangiu** [comment]
Evidence submitted on-chain: https://collectives.statescan.io/#/extrinsics/3683366-2

**Comment by bkchr** [comment]
Minimum promotion period for rank 2 to rank 3 is 365 days. This means that this will not work.

**Comment by acatangiu** [comment]
I have changed the evidence intention from `promote` (to rank 3) to `retain` (rank 2).

PTAL.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@acatangiu could you please update your on chain evidence?

**Comment by acatangiu** [comment]
Thank you!

Evidence submitted: https://collectives.statescan.io/#/extrinsics/3756027-2

P.S. seems like Statescan doesn't correctly render the `wish` parameter, opened an issue with them: https://github.com/opensquare-network/statescan-v2/issues/897

**Review by ggwpez — APPROVED** [review]

**Pull request merged**
